### ISSUE TITLE
AES Configuration Space

### ISSUE THREAD

**Issue by ben-marshall** [scarv/libscarv#6]
The AES configuration flags, and the code which uses them, is hard to understand.

1. Can we add some code when lets us query at run-time, the values of the configuration flags?
2. @phthinh - Can you please document the set of *valid* build flag configurations for AES, and also note
   which of these is used in the `generic`, `riscv` and `riscv-xcrypto` builds.

**Comment by ben-marshall** [comment]
@phthinh Can you please document which combinations of configuration flags for the AES implementation are valid?

The current `riscv-xcrypto` configuration ([Makefile here](https://github.com/scarv/libscarv/blob/master/Makefile.arch-riscv-xcrypto#L11)) for AES looks like this.
```
#CONF += -DCONF_AES_ENC_EXP_STEP_EXTERN                                      
CONF += -DCONF_AES_ROUND_PACK                                                
AES_TYPE  = space                                                            
CONF += -DCONF_AES_ENC_INIT_EXTERN                                           
CONF += -DCONF_AES_ENC_ITER_EXTERN                                           
CONF += -DCONF_AES_ENC_FINI_EXTERN                                           
CONF += -DCONF_AES_ENC_EXTERN      #comment this conf for split configuration
CONF += -DCONF_AES_DEC_INIT_EXTERN                                           
CONF += -DCONF_AES_DEC_ITER_EXTERN                                           
CONF += -DCONF_AES_DEC_FINI_EXTERN                                           
CONF += -DCONF_AES_DEC_EXTERN      #comment this conf for split configuration
```

Even with your description in #5 , I still don't know which combinations of these are valid and when.

For example, I can randomly comment out any of:
```
CONF += -DCONF_AES_ENC_INIT_EXTERN                                           
CONF += -DCONF_AES_ENC_ITER_EXTERN                                           
CONF += -DCONF_AES_ENC_FINI_EXTERN                                           
CONF += -DCONF_AES_ENC_EXTERN
CONF += -DCONF_AES_DEC_INIT_EXTERN                                           
CONF += -DCONF_AES_DEC_ITER_EXTERN                                           
CONF += -DCONF_AES_DEC_FINI_EXTERN                                           
CONF += -DCONF_AES_DEC_EXTERN
```
any everything still works.

But, if I uncomment 
```
#CONF += -DCONF_AES_ENC_EXP_STEP_EXTERN                  
```
then everything breaks, and I don't know why.

I also don't know how any of these flags affect things if `AES_TYPE` is set to `speed`.
- Just setting `AES_TYPE=speed` and keeping everything else the same causes the build to fail, because it can't find `aes_conf.h`.
- I also can't work out how to turn on the dedicated `xc.aes*` instructions without everything breaking.

Can you please document the set of valid configurations for AES? Something along the lines of
```
if AES_TYPE == speed
    if CONF_AES_ROUND_PACK
         <list of valid options>
    else
         <list of valid options>
    end
elif AES_TYPE == space
    if CONF_AES_ROUND_PACK
         <list of valid options>
    else
         <list of valid options>
    end
else
    invalid configuration
end
```
It doesn't need to be code. Just having a list of numberd configurations with the correct set of flags set for each one is fine.

**Comment by phthinh** [comment]
Currently, all the assemble implementations of AES only work with the configuration of  `AES_TYPE=space` and `CONF_AES_PRECOMP_RK` flag . `CONF_AES_ENC_EXP_STEP_EXTERN` configuration flag have not been verified in encryption/decryption yet. I think this flag for now is not valid. the set of configuration flags for  AES assembly implementations  with regard to `riscv` and riscv-xcrypto` are as follow:
### For `ARCH= riscv`:
The assembly functions are only implemented in PACK mode so the `CONF_AES_ROUND_PACK` flags is required to be set. 
- The configuration below is for assemble implementations of AES in which the round function is not split.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
CONF += -DCONF_AES_ROUND_PACK            
CONF += -DCONF_AES_ENC_EXTERN      
CONF += -DCONF_AES_DEC_EXTERN
```
- The configuration for splitting round function into three sub-functions ` *_init, *_iter, *_fini`.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
CONF += -DCONF_AES_ROUND_PACK            
# CONF += -DCONF_AES_ENC_EXTERN      
# CONF += -DCONF_AES_DEC_EXTERN
CONF += -DCONF_AES_ENC_INIT_EXTERN
CONF += -DCONF_AES_ENC_ITER_EXTERN
CONF += -DCONF_AES_ENC_FINI_EXTERN
CONF += -DCONF_AES_DEC_INIT_EXTERN
CONF += -DCONF_AES_DEC_ITER_EXTERN
CONF += -DCONF_AES_DEC_FINI_EXTERN
```
Two flags `CONF_AES_ENC_EXTERN, CONF_AES_DEC_EXTERN` need to be unset. Six flags `CONF_AES_ENC_INIT_EXTERN, CONF_AES_ENC_ITER_EXTERN, CONF_AES_ENC_FINI_EXTERN, CONF_AES_DEC_INIT_EXTERN, CONF_AES_DEC_ITER_EXTERN, CONF_AES_DEC_FINI_EXTERN` can be arbitrarily set to chose the assemble implementations for the corresponding functions.

### For `ARCH= riscv-xcrypto`:
The assembly functions are implemented using AES extension instructions, e.g., xc.aessub, xc.aesmix, in UNPACK mode, otherwise, the assembly functions are implemented using other instructions of `xcrypto`, e.g. `xc.scatter, xc.gather`.
8 flags `CONF_AES_ENC_EXTERN, CONF_AES_DEC_EXTERN, CONF_AES_ENC_INIT_EXTERN, CONF_AES_ENC_ITER_EXTERN, CONF_AES_ENC_FINI_EXTERN, CONF_AES_DEC_INIT_EXTERN, CONF_AES_DEC_ITER_EXTERN, CONF_AES_DEC_FINI_EXTERN` are used similarly to `ARCH=riscv` case for splitting or un-splitting round functions.
- The configuration for assemble implementations of unsplit round function using AES extension instructions.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
# CONF += -DCONF_AES_ROUND_PACK            
CONF += -DCONF_AES_ENC_EXTERN      
CONF += -DCONF_AES_DEC_EXTERN
```
- The configuration for assemble implementations of split round function using AES extension instructions.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
# CONF += -DCONF_AES_ROUND_PACK            
# CONF += -DCONF_AES_ENC_EXTERN      
# CONF += -DCONF_AES_DEC_EXTERN
CONF += -DCONF_AES_ENC_INIT_EXTERN
CONF += -DCONF_AES_ENC_ITER_EXTERN
CONF += -DCONF_AES_ENC_FINI_EXTERN
CONF += -DCONF_AES_DEC_INIT_EXTERN
CONF += -DCONF_AES_DEC_ITER_EXTERN
CONF += -DCONF_AES_DEC_FINI_EXTERN
```
- The configuration for assemble implementations of unsplit round function using other `xcrypto` instructions.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
CONF += -DCONF_AES_ROUND_PACK            
CONF += -DCONF_AES_ENC_EXTERN      
CONF += -DCONF_AES_DEC_EXTERN
```
- The configuration for assemble implementations of split round function using other `xcrypto` instructions.
```
AES_TYPE  = space 
CONF += -DCONF_AES_PRECOMP_RK
CONF += -DCONF_AES_ROUND_PACK            
# CONF += -DCONF_AES_ENC_EXTERN      
# CONF += -DCONF_AES_DEC_EXTERN
CONF += -DCONF_AES_ENC_INIT_EXTERN
CONF += -DCONF_AES_ENC_ITER_EXTERN
CONF += -DCONF_AES_ENC_FINI_EXTERN
CONF += -DCONF_AES_DEC_INIT_EXTERN
CONF += -DCONF_AES_DEC_ITER_EXTERN
CONF += -DCONF_AES_DEC_FINI_EXTERN
```
